[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
nen-emulator = { path = "nen-emulator" }
tomboy-emulator = { path = "tomboy-emulator" }

sdl2 = "0.37.0"
zip = "2.2.2"
bincode = "1.3.3"
ron = "0.8.1"

[dev-dependencies]
